title: beepboopblog
author: Maciej Bryła
description: RE blog for documenting my progress and hopefully helping someone.

footer-links:
  email: 123123@123.com
  linkedin: blablabla
  twitter: blablabla
  
version: v3.9.3

exclude:
  README.md
